// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// DotExecutor is an autogenerated mock type for the DotExecutor type
type DotExecutor struct {
	mock.Mock
}

// Render provides a mock function with given fields: dotfile, outfile
func (_m *DotExecutor) Render(dotfile string, outfile string) error {
	ret := _m.Called(dotfile, outfile)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(dotfile, outfile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
